version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/go/src/github.com/sekky0905/nuxt-vue-go-chat
    command: bash -c 'cd /go/src/github.com/sekky0905/nuxt-vue-go-chat/server && go run *.go'
    ports:
      - "8080:8080"
    container_name: app
